version: "3"

services:
  postgres:
    image: postgres:latest
    command: -c 'max_connections=200'
    environment:
      - POSTGRES_PASSWORD=""
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql
    networks:
      - TLBCluster

  tlb:
    image: tlbml:0.1.0
    command: uvicorn main:app --host "0.0.0.0" --port "2580"
    volumes:
      - "tlb:/app/storage"
      - "../.penv:/app/.env"
      - "/weights/best.pt:/app/best.pt"
    ports:
      - "2580:2580"
    networks:
      - TLBCluster
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 20
        window: 120s

volumes:
  tlb:
    driver: local
  data:

networks:
  TLBCluster: